### ISSUE TITLE
GBSDTOnlinePredictor learning_rate<1 bug

### ISSUE THREAD

**Issue by junphine** [yuantiku/ytk-learn#10]
如果learning_rate值小于1，比如0.2 
在计算score过程中，score取值为 fx += learningRate * mu[0]; 

训练好的gradient_boosting模型预测值严重偏离正常值，除非learningRate =1。

**Comment by scharoun** [comment]
非常谢谢，近期会修复

2018-04-25 14:04 GMT+08:00 junphine <notifications@github.com>:

**Comment by scharoun** [comment]
你好，这个不是 bug，是最后一个树在训练的时候是没有乘learningrate，在预测的时候乘了，所以有点误差(gbdt也是这样的，因为gbdt树多，后面预测值都很小，所以看不出来)，后面softtree都改成最后一棵树不乘learningrate，跟训练时候保持一致
