### ISSUE TITLE
windows can not load model

### ISSUE THREAD

**Issue by aducode** [yuantiku/ytk-learn#11]
[LocalFileSystem#L133](https://github.com/yuantiku/ytk-learn/blob/master/src/main/java/com/fenbi/ytklearn/fs/LocalFileSystem.java#L133)
```java
private static boolean isHiddenFile(File file) {
        // file isHidden
        if (file.isHidden()) {
            return true;
        } else {
            File parent = file.getParentFile();
            if (parent == null) {
                return false;
            }
            return isHiddenFile(parent);
        }
    }
```
```java
// in windows
File file = new File("C:\\");
System.out.println(file.isHidden()); // is true
```
when load model in windows, because the recursive method isHiddenFile, it dosen't work

**Comment by scharoun** [comment]
The method "isHiddenFile" is only invoked by recurGetPaths only when the file is not directory~
