### ISSUE TITLE
which class file  implements  SVM    algorithm?

### ISSUE THREAD

**Issue by marshalWS** [yuantiku/ytk-learn#3]
Ytk-learn is a distributed machine learning library which implements most of popular machine learning algorithms(GBDT, GBRT, Mixture Logistic Regression, Gradient Boosting Soft Tree, Factorization Machines, Field-aware Factorization Machines, Logistic Regression, Softmax, SVM).
where is **SVM** model?

**Comment by scharoun** [comment]
Svm only supports hinge loss now, including binary and multiclass classification, https://github.com/yuantiku/ytk-learn/blob/master/docs/models.md

**Comment by marshalWS** [comment]
ok, which model  corresponding to SVM ?

**Comment by marshalWS** [comment]
OK
