### ISSUE TITLE
分布式训练算法

### ISSUE THREAD

**Issue by junphine** [yuantiku/ytk-learn#7]
不想使用spark或者hadoop，
比如，我有3台机器，启动3个进程的TrainWorker，训练样本分成三份，每个进程使用不同的训练样本，每个TrainWorker启动8个线程。

CommMaster启动参数设置为接收3个slave。

这样能训练好模型吗？

**Comment by scharoun** [comment]
完全没问题呀，但是得注意你的样本是放在各自的物理机器上(需要自己手动划分数据)，还是放在hadoop公共的地方(会自动划分好数据)

**Comment by junphine** [comment]
了解。ytk-mp4j设计的不错！

**Comment by scharoun** [comment]
哈哈，谢谢
