### ISSUE TITLE
FFMOnlinePredictor bug

### ISSUE THREAD

**Issue by junphine** [yuantiku/ytk-learn#9]
line: 
58: fieldDelim = config.getString("field_delim");   // should data.delim.field_delim
59: fieldDictPath = config.getString("model.field_dict_path");
60: maxFeatureNum = config.getInt("max_line_feature_num");  // maybe feature.max_line_feature_num 

106:  iterators = fs.read(Arrays.asList(modelParams.data_path)); // should modelParams.data_path
115: if (fieldSize != (info.length - 5) / K) {         //  should info.length - 2

**Comment by junphine** [comment]
195:          System.arraycopy(w, 1, assist, cidx * stride, stride); 

assist is double array , w is float array throw ArrayStoreException

**Comment by scharoun** [comment]
fixed! thx
